CREATE SCHEMA IF NOT EXISTS erp;


CREATE TABLE IF NOT EXISTS erp.base_table (
    id          UUID                        PRIMARY KEY DEFAULT uuidv4(),
    created_at  TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMP WITH TIME ZONE
);


CREATE OR REPLACE FUNCTION erp.do_not_change() RETURNS TRIGGER
    VOLATILE
    LANGUAGE plpgsql AS $$ BEGIN
    RAISE EXCEPTION 'Cannot modify table %.%', TG_TABLE_SCHEMA, TG_TABLE_NAME;
END; $$;


CREATE OR REPLACE TRIGGER do_not_change
    BEFORE INSERT OR UPDATE OR DELETE
    ON erp.base_table
    FOR EACH ROW
EXECUTE PROCEDURE erp.do_not_change();
